development: &development
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  host: localhost
  pool: 5
  username: postgres
  password: secret

test:
  <<: *development
  host: localhost
  username: postgres
  password: secret
  database: test_app_test
